### PR TITLE
rev to 3.0.0-beta in preparation for publishing

### PR DESCRIPTION
**Pull request by devoncarew**
- rev to 3.0.0-beta in preparation for publishing

I'd like to publish this as `3.0.0-beta` (pre-release) in order to run the current lint set through a few code bases; that'll let us make sure the changes in analysis are ~what we'd expect.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by pq** [comment]
I've made a late-breaking proposal for 3.0 in https://github.com/dart-lang/lints/issues/154.

If you feel comfortable, I'm OK with landing this before we reach a decision on that. (I think we can still remove `prefer_void_to_null` for 3.0 even if there's a beta out that still has it.)

**Review by pq — APPROVED** [review]

**Comment by devoncarew** [comment]
> I've made a late-breaking proposal for 3.0 in #154.
> 
> If you feel comfortable, I'm OK with landing this before we reach a decision on that. (I think we can still remove `prefer_void_to_null` for 3.0 even if there's a beta out that still has it.)

Gotcha; this beta may not be the final word for `3.0.0`; we still need to look into the analysis toggles around unintentional use of dynamic. We'll still have time to look at #154 and see if we think it should be in this release or no.

**Comment by devoncarew** [comment]
Looks like publishing automation here failed - `Pubspec version (3.0.0-beta) and git tag (v3.0.0-beta) don't agree.`. Perhaps due to incomplete handling of `-beta` versions? I'll manually publish from the tag and file an issue on firehose.

**Comment by devoncarew** [comment]
https://github.com/dart-lang/ecosystem/issues/176

**Pull request merged**
